KOBJS+= kernel/fs/callbacks.o \
		kernel/fs/close.o \
		kernel/fs/dirent.o \
		kernel/fs/fcntl.o \
		kernel/fs/file.o \
		kernel/fs/fs.o \
		kernel/fs/initrd.o \
		kernel/fs/inode.o \
		kernel/fs/mminode.o \
		kernel/fs/open.o \
		kernel/fs/ramfs.o \
		kernel/fs/read_write.o \
		kernel/fs/socket.o \
		kernel/fs/stat.o \
		kernel/fs/sync.o \
		kernel/fs/sys.o \
		kernel/fs/link.o \
		kernel/fs/path.o

